function generateRandomPrice(min, max) {
  const price = Math.random() * (max - min) + min;
  return price.toFixed(2);
}

const hardcodedManga = [
  {
    title: `One Punch-Man`,
    description: `After rigorously training for three years...`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/80661.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/44347/One_Punch-Man`,
    myanimelist_id: 44347,
    price: `$15.13`,
  },

  {
    title: `Bleach`,
    description: `Ichigo Kurosaki is an ordinary high schooler...`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/109986.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/12/Bleach`,
    myanimelist_id: 12,
    price: `$14.21`,
  },

  {
    title: `Mob Psycho 100`,
    description: `Eighth-grader Shigeo "Mob" Kageyama has tapped into his inner wellspring of psychic prowess...`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/165970.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/108009/Mob_Psycho_100`,
    myanimelist_id: 108009,
    price: `$13.25`,
  },

  {
    title: `Naruto`,
    description: `Whenever Naruto Uzumaki proclaims that he will someday become the Hokage—a title bestowed upon the best ninja in the Village Hidden in the Leaves—no one takes him seriously. Since birth, Naruto has be...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/249658.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/11/Naruto`,
    myanimelist_id: 11,
    price: `$11.53`,
  },

  {
    title: `Boruto: Naruto Next Generations`,
    description: `Naruto Uzumaki has finally achieved his dream of becoming Hokage, the leader of the Hidden Leaf Village that he spent his teenage years fighting to protect. Naruto and his peers now live in a world of...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/181968.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/95210/Boruto__Naruto_Next_Generations`,
    myanimelist_id: 95210,
    price: `$20.62`,
  },

  {
    title: `Bleach`,
    description: `For as long as he can remember, high school student Ichigo Kurosaki has been able to see the spirits of the dead, but that has not stopped him from leading an ordinary life. One day, Ichigo returns ho...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/180031.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/12/Bleach`,
    myanimelist_id: 12,
    price: `$16.14`,
  },

  {
    title: `Bleach: Can't Fear Your Own World`,
    description: `The Quincies's Thousand Year Blood War is over, but the embers of turmoil still smolder in the Soul Society. Tokinada Tsunayashiro, elevated to head of his clan after a slew of assassinations take out...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/291343.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/106602/Bleach__Cant_Fear_Your_Own_World`,
    myanimelist_id: 106602,
    price: `$15.38`,
  },

  {
    title: `Bleach: Spirits Are Forever with You`,
    description: `Follows the events during the seventeen month timeskip after the Aizen battle, involving the eighth generation Kenpachi and a revived Szayel Aporro Granz.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/76783.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/43605/Bleach__Spirits_Are_Forever_with_You`,
    myanimelist_id: 43605,
    price: `$16.90`,
  },

  {
    title: `Mob Psycho 100`,
    description: `Shigeo "Mob" Kageyama is an eighth-grade student blessed with extraordinary psychic powers. However, Mob decides to suppress his abilities in public due to its destructive and conspicuous nature. To k...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/204842.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/60783/Mob_Psycho_100`,
    myanimelist_id: 60783,
    price: `$17.74`,
  },

  {
    title: `Fairy Tail`,
    description: `In the mystical realm of Earth Land, magic exists at the core of everyday life for its inhabitants, from transportation to utilities and everything in between. However, even with all its benefits, mag...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/198604.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/598/Fairy_Tail`,
    myanimelist_id: 598,
    price: `$14.45`,
  },

  {
    title: `Fairy Tail Gaiden`,
    description: `Fairy Tail Gaiden is a trilogy detailing the adventures of Sting and Rogue, Gajeel and Levy, and Laxus and the Thunder Tribe in separate volumes. 1. Kengami no Souryuu (Twin Dragons of Sabertooth) 2....read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/171669.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/91971/Fairy_Tail_Gaiden`,
    myanimelist_id: 91971,
    price: `$16.62`,
  },

  {
    title: `Fairy Tail: City Hero`,
    description: `A spinoff from the Fairy Tail universe—with Lucy now on assignment as a police officer—and lots of your old friends appearing in an unexpected new setting! The Magic Police can handle any case! A hear...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/219511.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/116463/Fairy_Tail__City_Hero`,
    myanimelist_id: 116463,
    price: `$21.54`,
  },

  {
    title: `Fairy Tail Zerø`,
    description: `Long before she would found Fairy Tail, first master Mavis Vermillion is left under the care of the Red Lizard guild. Abused and belittled at every opportunity, she is forced to complete difficult cho...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/167384.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/69903/Fairy_Tail_Zerø`,
    myanimelist_id: 69903,
    price: `$15.53`,
  },

  {
    title: `Fairy Tail: 100 Years Quest`,
    description: `The 100 Years Quest: a mission so challenging and hazardous that it has remained unaccomplished for over a century. While countless mages have attempted to take on this gruelling objective, their resu...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/213604.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/114701/Fairy_Tail__100_Years_Quest`,
    myanimelist_id: 114701,
    price: `$20.85`,
  },

  {
    title: `Edens Zero`,
    description: `On the planet of Granbell, Shiki has led an isolated life growing up as the only human in Granbell Kingdom—an amusement park operated by machines. However, that changes when Rebecca Bluegarden and her...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/212094.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/114548/Edens_Zero`,
    myanimelist_id: 114548,
    price: `$18.79`,
  },

  {
    title: `Re:Zero kara Hajimeru Isekai Seikatsu`,
    description: `Exiting the convenience store, Subaru Natsuki emerges to a busy town inhabited by humans and demi-humans. Using dragons and carriages as transportation, the town is clearly not the modern-day Japan th...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/129447.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/74697/Re_Zero_kara_Hajimeru_Isekai_Seikatsu`,
    myanimelist_id: 74697,
    price: `$18.17`,
  },

  {
    title: `Eden no Ori`,
    description: `Just a few hours ago, Akira Sengoku was having fun with his classmates on their flight back to Japan from a school trip in Guam. Now, he finds himself all alone in a jungle after the plane mysteriousl...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/56963.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/12586/Eden_no_Ori`,
    myanimelist_id: 12586,
    price: `$16.59`,
  },

  {
    title: `Shingeki no Kyojin`,
    description: `Hundreds of years ago, horrifying creatures which resembled humans appeared. These mindless, towering giants, called Titans, proved to be an existential threat, as they preyed on whatever humans they...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/37846.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/23390/Shingeki_no_Kyojin`,
    myanimelist_id: 23390,
    price: `$21.54`,
  },

  {
    title: `Shingeki no Kyojin: Before the Fall`,
    description: `A baby is found crying in a mass of Titan vomit, amidst the dead titan flames. The child is called "child of titan" and is essentially hated by the people inside the walls. He also seems to grow unnat...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/128683.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/57795/Shingeki_no_Kyojin__Before_the_Fall`,
    myanimelist_id: 57795,
    price: `$13.53`,
  },

  {
    title: `Shingeki no Kyojin: Lost Girls`,
    description: `Joining the Military Police has provided Annie Leonhart with a quiet life within the walls. However, not everything is as tranquil as it might seem. Tormented by her past sins, Annie must carry out a...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/177247.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/91047/Shingeki_no_Kyojin__Lost_Girls`,
    myanimelist_id: 91047,
    price: `$11.44`,
  },

  {
    title: `Jujutsu Kaisen`,
    description: `Hidden in plain sight, an age-old conflict rages on. Supernatural monsters known as "Curses" terrorize humanity from the shadows, and powerful humans known as "Jujutsu" sorcerers use mystical arts to...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/210341.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/113138/Jujutsu_Kaisen`,
    myanimelist_id: 113138,
    price: `$13.15`,
  },

  {
    title: `Jujutsu Kaisen 0: Tokyo Toritsu Jujutsu Koutou Senmon Gakkou`,
    description: `Yuuta Okkotsu is haunted. Ever since his childhood friend Rika died in a traffic accident, her ghost has stuck with him. But her spirit does not appear as the sweet girl Yuuta once knew. Instead, she...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/219336.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/115710/Jujutsu_Kaisen_0__Tokyo_Toritsu_Jujutsu_Koutou_Senmon_Gakkou`,
    myanimelist_id: 115710,
    price: `$19.51`,
  },

  {
    title: `Boku no Hero Academia`,
    description: `One day, a four-year-old boy came to a sudden realization: the world is not fair. Eighty percent of the world's population wield special abilities, known as "quirks," which have given many the power t...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/209370.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/75989/Boku_no_Hero_Academia`,
    myanimelist_id: 75989,
    price: `$17.35`,
  },

  {
    title: `Dandadan`,
    description: `After being aggressively rejected, Momo Ayase finds herself sulking when she stumbles across a boy being bullied. Saved by her rash kindness, the occult-obsessed boy attempts to speak to her about sup...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/248746.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/135496/Dandadan`,
    myanimelist_id: 135496,
    price: `$20.57`,
  },

  {
    title: `Bocchi the Rock!`,
    description: `High school student Hitori "Bocchi" Gotou has no social life or any friends—unless you count her guitar. She dreams of creating a school band in the hopes that using her instrument will elevate her so...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/224954.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/118568/Bocchi_the_Rock`,
    myanimelist_id: 118568,
    price: `$15.38`,
  },

  {
    title: `Spy x Family`,
    description: `For the agent known as "Twilight," no order is too tall if it is for the sake of peace. Operating as Westalis' master spy, Twilight works tirelessly to prevent extremists from sparking a war with neig...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/219741.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/119161/Spy_x_Family`,
    myanimelist_id: 119161,
    price: `$19.13`,
  },

  {
    title: `Undead Unluck`,
    description: `After reading the conclusion of her favorite manga series, Fuuko Izumo finally feels ready to end her existence. For the past 10 years, Fuuko has been afflicted by a condition that brings extreme misf...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/289700.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/123956/Undead_Unluck`,
    myanimelist_id: 123956,
    price: `$13.06`,
  },

  {
    title: `Ao no Hako`,
    description: `Taiki Inomata is a student enthusiastic about sports and aspires to arrive first at his school's blue-box gymnasium every day. Unfortunately, his morning smile quickly turns into a frown as he loses a...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/233910.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/128694/Ao_no_Hako`,
    myanimelist_id: 128694,
    price: `$20.29`,
  },

  {
    title: `Ao no Exorcist`,
    description: `After a fight with his foster father Shirou Fujimoto, Rin Okumura's life is transformed overnight when Rin is revealed to be the son of the demon lord Satan, king of the demonic realm of Gehenna. Soon...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/188810.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/13492/Ao_no_Exorcist`,
    myanimelist_id: 13492,
    price: `$18.69`,
  },

  {
    title: `Ao Haru Ride`,
    description: `While most girls desire popularity among boys, Futaba Yoshioka wants the exact opposite. After attracting many admirers back in middle school which resulted in her being shunned by her female classmat...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/256907.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/24294/Ao_Haru_Ride`,
    myanimelist_id: 24294,
    price: `$11.10`,
  },

  {
    title: `Kagurabachi`,
    description: `Young Chihiro spends his days training under his famous swordsmith father. One day he hopes to become a great sword-maker himself. The goofy father and the serious son—they thought these days would la...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/296327.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/162479/Kagurabachi`,
    myanimelist_id: 162479,
    price: `$18.65`,
  },

  {
    title: `Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen`,
    description: `Considered a genius due to having the highest grades in the country, Miyuki Shirogane leads the prestigious Shuchiin Academy's student council as its president, working alongside the beautiful and wea...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/188896.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/90125/Kaguya-sama_wa_Kokurasetai__Tensai-tachi_no_Renai_Zunousen`,
    myanimelist_id: 90125,
    price: `$13.04`,
  },

  {
    title: `Yozakura Quartet`,
    description: `Hime is a superheroine. Ao can read minds. Kotoha can conjure up anything with the right word. And Akina... well, he's just a regular guy, surrounded by three supergirls! Together, they protect the to...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/153963.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/2060/Yozakura_Quartet`,
    myanimelist_id: 2060,
    price: `$13.18`,
  },

  {
    title: `Yozakura-san Chi no Daisakusen`,
    description: `High school student Taiyou Asano has been socially inept ever since his family died in a car crash. The only person he can properly interact with is his childhood friend, Mutsumi Yozakura—the head of...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/226602.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/121426/Yozakura-san_Chi_no_Daisakusen`,
    myanimelist_id: 121426,
    price: `$18.94`,
  },

  {
    title: `Witch Watch`,
    description: `Nico Wakatsuki has finished her six years of witch training and is moving back to town by herself. As a new witch, she must choose a familiar to accompany her. However, unlike the other witches, she w...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/245786.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/133545/Witch_Watch`,
    myanimelist_id: 133545,
    price: `$17.13`,
  },

  {
    title: `Burn the Witch`,
    description: `Ninny Spangcole is the leader of popular girl group, Cecile Die Twice, but her ambitions stretch far beyond a successful music career. In the hidden underground world of Reverse London, Ninny and her...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/238094.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/129370/Burn_the_Witch`,
    myanimelist_id: 129370,
    price: `$20.67`,
  },

  {
    title: `Katekyou Hitman Reborn!`,
    description: `The life of Tsunayoshi "No-Good Tsuna" Sawada is a complete wreck. Terrible grades, horrible fitness, and a non-existent social life means he has no reason to attend school, especially after discoveri...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/253085.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/47/Katekyou_Hitman_Reborn`,
    myanimelist_id: 47,
    price: `$13.07`,
  },

  {
    title: `Katekyou Hitman Reborn! Secret Bullet`,
    description: `Each novel contains several short stories, many of which were originally serialized in Jump Square; however, each novel also contains at least one new story (the titular story), specially written for...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/26013.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/17288/Katekyou_Hitman_Reborn_Secret_Bullet`,
    myanimelist_id: 17288,
    price: `$21.57`,
  },

  {
    title: `Doraemon`,
    description: `Doraemon is cat shaped robot from the future traveling all the way back to the 20th century in order to help Nobi Nobita, a lazy kid with nothing really going for him. Nobi is bad at sports, his grade...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/298132.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1032/Doraemon`,
    myanimelist_id: 1032,
    price: `$20.20`,
  },

  {
    title: `Hajime no Ippo`,
    description: `Makunouchi Ippo is a 16-year-old high school student who helps his mother run the family business. His hefty workload impedes on his social life, making him an easy target for bullies. One day, while...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/250313.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/7/Hajime_no_Ippo`,
    myanimelist_id: 7,
    price: `$13.05`,
  },

  {
    title: `Kamisama Hajimemashita`,
    description: `Nanami Momozono is a high schooler who has a lot on her plate. Her father had evaded his enormous gambling debts by escaping town, which resulted in his daughter being evicted by the debt collectors....read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/269698.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/8157/Kamisama_Hajimemashita`,
    myanimelist_id: 8157,
    price: `$18.48`,
  },

  {
    title: `Kimetsu no Yaiba`,
    description: `Tanjirou Kamado lives with his impoverished family on a remote mountain. As the oldest sibling, he took upon the responsibility of ensuring his family's livelihood after the death of his father. On a...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/179023.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/96792/Kimetsu_no_Yaiba`,
    myanimelist_id: 96792,
    price: `$16.72`,
  },

  {
    title: `Kimetsu no Yaiba Gaiden`,
    description: `1-2. Kimetsu no Yaiba: Tomioka Giyuu Gaiden 3-4. Kimetsu no Yaiba: Rengoku Kyoujurou Gaiden 5. Kimetsu no Aima!`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/238006.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/131706/Kimetsu_no_Yaiba_Gaiden`,
    myanimelist_id: 131706,
    price: `$11.54`,
  },

  {
    title: `Hokuto no Ken`,
    description: `The year is 199X. The Earth has been devastated by nuclear war. The seas have dried up and the land is cracked and desolate. Most living things on the planet have become extinct apart from the human r...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/258755.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1149/Hokuto_no_Ken`,
    myanimelist_id: 1149,
    price: `$13.75`,
  },

  {
    title: `JoJo no Kimyou na Bouken Part 9: The JoJoLands`,
    description: `O'ahu, present day. Dua Lipa is the trending musician, and COVID is still a major concern. On this island lives a 15-year-old boy named Jodio Joestar. Living with his brother and mother, he acts as a...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/286969.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/139629/JoJo_no_Kimyou_na_Bouken_Part_9__The_JoJoLands`,
    myanimelist_id: 139629,
    price: `$12.95`,
  },

  {
    title: `JoJo no Kimyou na Bouken Part 6: Stone Ocean`,
    description: `In Florida, 2011, Jolyne Kuujou sits in a jail cell like her father Joutarou once did; yet this situation is not of her own choice. Framed for a crime she didn't commit, and manipulated into serving a...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/255379.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/3009/JoJo_no_Kimyou_na_Bouken_Part_6__Stone_Ocean`,
    myanimelist_id: 3009,
    price: `$20.74`,
  },

  {
    title: `JoJo no Kimyou na Bouken Part 8: JoJolion`,
    description: `In 2011, childhood friends Yasuho Hirose and Joushuu Higashikata discover a naked man buried in the ground just outside the town of Morioh. The man has no memory of his name or previous life; the only...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/179885.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/25515/JoJo_no_Kimyou_na_Bouken_Part_8__JoJolion`,
    myanimelist_id: 25515,
    price: `$20.24`,
  },

  {
    title: `Ojojojo`,
    description: `Haru Jigokumeguri is the eldest daughter of a highly successful businessman, gifted with both intelligence and beauty. Kawayanagi Tsurezure is an eccentric boy who dresses in 20th century fashion and...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/131785.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/76083/Ojojojo`,
    myanimelist_id: 76083,
    price: `$19.34`,
  },

  {
    title: `JoJo no Kimyou na Bouken Part 5: Ougon no Kaze`,
    description: `Naples, 2001. Giorno Giovanna is a small-time crook with one big dream—to become a "Gang-Star." No ordinary thief, Giorno has a connection to the remarkable Joestar bloodline, and possesses a Stand na...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/269912.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/3008/JoJo_no_Kimyou_na_Bouken_Part_5__Ougon_no_Kaze`,
    myanimelist_id: 3008,
    price: `$16.98`,
  },

  {
    title: `JoJo's Bizarre Adventure: Over Heaven`,
    description: `A novel centered on Dio.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/270480.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/32347/JoJos_Bizarre_Adventure__Over_Heaven`,
    myanimelist_id: 32347,
    price: `$11.12`,
  },

  {
    title: `Daily JoJo`,
    description: `Eunjo is an ordinary office worker who lives by the personal mantra, "There's always tomorrow!" She's lazy, messy, and clueless when it comes to looking presentable. Her colleague Wan Jo is the polar...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/267217.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/147589/Daily_JoJo`,
    myanimelist_id: 147589,
    price: `$17.58`,
  },

  {
    title: `JoJo no Kimyou na Bouken Part 2: Sentou Chouryuu`,
    description: `America, 1938. Robert E. O. Speedwagon, his foundation, and Straits venture to Mexico to gather more information about the enigmatic Stone Masks. While excavating the ruins, Speedwagon's men are slaug...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/269908.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1630/JoJo_no_Kimyou_na_Bouken_Part_2__Sentou_Chouryuu`,
    myanimelist_id: 1630,
    price: `$21.37`,
  },

  {
    title: `The Book: JoJo's Bizarre Adventure 4th Another Day`,
    description: `The novel is about a normal day in Morioh, from the point of view of a new character named Takuma Hasumi. His stand is called The Book, has the appearance of a normal book, and possesses the power to...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/60351.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/32991/The_Book__JoJos_Bizarre_Adventure_4th_Another_Day`,
    myanimelist_id: 32991,
    price: `$21.01`,
  },

  {
    title: `JoJo no Kimyou na Bouken Part 1: Phantom Blood`,
    description: `While the gold rush takes Europe by storm, a young Jonathan Joestar lives a life of luxury with his father at their estate in Liverpool, England. Jonathan, known by his peers as JoJo, spends his days...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/269907.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1517/JoJo_no_Kimyou_na_Bouken_Part_1__Phantom_Blood`,
    myanimelist_id: 1517,
    price: `$19.10`,
  },

  {
    title: `Yuu☆Yuu☆Hakusho`,
    description: `Fourteen-year-old thug Yuusuke Urameshi spends his days skipping school and causing trouble for the adults in his life. Yuusuke regularly engages in street brawls against rival Kazuma Kuwabara and rid...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/250027.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/53/Yuu☆Yuu☆Hakusho`,
    myanimelist_id: 53,
    price: `$15.34`,
  },

  {
    title: `Rurouni Kenshin: Meiji Kenkaku Romantan`,
    description: `Ten years have passed since the end of Bakumatsu, an era of war that saw the uprising of citizens against the Tokugawa shogunate. The revolutionaries wanted to create a time of peace, and a thriving c...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/127583.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/22/Rurouni_Kenshin__Meiji_Kenkaku_Romantan`,
    myanimelist_id: 22,
    price: `$11.45`,
  },

  {
    title: `Rurouni Kenshin: Meiji Kenkaku Romantan - Hokkaido-hen`,
    description: `It is the 16th year of the Meiji era. Five years have passed since Kenshin Himura stopped the uprising of Makoto Shishio. Though the flames of his budding revolution were extinguished, the scars left...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/211412.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/105837/Rurouni_Kenshin__Meiji_Kenkaku_Romantan_-_Hokkaido-hen`,
    myanimelist_id: 105837,
    price: `$12.94`,
  },

  {
    title: `Rurouni Kenshin: Tokuhitsuban`,
    description: `This version will be a remake of the original series that revisits the encounters of 'Himura Kenshin' with 'Kamiya Kaoru' and 'Myojin Yahiko.'`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/132973.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/37303/Rurouni_Kenshin__Tokuhitsuban`,
    myanimelist_id: 37303,
    price: `$15.36`,
  },

  {
    title: `Hana yori Dango`,
    description: `Tsukushi Makino, a working-class girl, attends an elite elevator school called Eitoku Academy, populated by children from rich, high-society families. She is the "weed" of the school surrounded by all...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/27280.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/877/Hana_yori_Dango`,
    myanimelist_id: 877,
    price: `$19.63`,
  },

  {
    title: `Major`,
    description: `The story of Major follows the life of Gorou Honda, from kindergarten to being a professional baseball player, seeking and overcoming tremendous challenges.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/185602.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/10978/Major`,
    myanimelist_id: 10978,
    price: `$20.54`,
  },

  {
    title: `Kuroko no Basket`,
    description: `Teikou Middle School is famous for its highly renowned basketball team, which produced the famed "Generation of Miracles": a team of five prodigies, each with their own unique abilities, considered to...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/244299.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/11652/Kuroko_no_Basket`,
    myanimelist_id: 11652,
    price: `$19.42`,
  },

  {
    title: `Kuroko no Basket: Extra Game`,
    description: `The college basketball team Strky, comprised of familiar faces from past Interhigh tournaments, is ready to face off against the Jabberwock, a popular American street basketball team that has just arr...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/163711.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/83807/Kuroko_no_Basket__Extra_Game`,
    myanimelist_id: 83807,
    price: `$11.74`,
  },

  {
    title: `Kuroko no Basket: Replace`,
    description: `Who were the legendary "Generation of Miracles" that led Teikou Middle School to three consecutive basketball championship titles? The group consisted of five prodigies—alongside their "Phantom Sixth...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/164178.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/42737/Kuroko_no_Basket__Replace`,
    myanimelist_id: 42737,
    price: `$14.51`,
  },

  {
    title: `Kuroko no Basket: Replace Plus`,
    description: `The "Generation of Miracles" is a name given to a team of five middle school basketball prodigies who led Teikou Middle School to win three consecutive championship titles. Underneath all of the prest...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/157861.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/85900/Kuroko_no_Basket__Replace_Plus`,
    myanimelist_id: 85900,
    price: `$11.39`,
  },

  {
    title: `Haikyuu!!`,
    description: `The whistle blows. The ball is up. A dig. A set. A spike. Volleyball. A sport where two teams face off, separated by a formidable, wall-like net. The "Little Giant," standing at only 170 centimeters,...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/258225.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/35243/Haikyuu`,
    myanimelist_id: 35243,
    price: `$14.64`,
  },

  {
    title: `Tennis no Oujisama`,
    description: `Seishun Academy is home to one of the best middle school tennis teams in all of Japan. Freshman tennis prodigy Ryouma Echizen enrolls in the prestigious institution with his eyes set on claiming a reg...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/153238.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/49/Tennis_no_Oujisama`,
    myanimelist_id: 49,
    price: `$12.99`,
  },

  {
    title: `Shin Tennis no Oujisama`,
    description: `Fifty nationally ranked middle school tennis players receive an invitation to join the Japan U-17 training camp—an exclusive tennis camp that was previously open only to high school players. Amongst t...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/153234.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/12965/Shin_Tennis_no_Oujisama`,
    myanimelist_id: 12965,
    price: `$17.34`,
  },

  {
    title: `Nanatsu no Taizai`,
    description: `In a world where injustice prevails, the Holy Knights of Britannia protect their homeland with their unparalleled magic and strength. Their most sought-after targets are "The Seven Deadly Sins": a gro...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/153111.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/44485/Nanatsu_no_Taizai`,
    myanimelist_id: 44485,
    price: `$19.49`,
  },

  {
    title: `Mokushiroku no Yonkishi`,
    description: `Percival has always lived with his grandfather on God's Finger, a remote haven that sits high above the clouds. And though he loves the simple life, he secretly longs for adventure. But Percival's lif...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/243307.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/128691/Mokushiroku_no_Yonkishi`,
    myanimelist_id: 128691,
    price: `$19.13`,
  },

  {
    title: `Black Jack`,
    description: `Black Jack is an "unregistered" doctor with a clouded, mysterious past. He works with his little assistant Pinoko (who has a massive crush on the doctor), dealing with medical cases not very well know...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/266117.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1600/Black_Jack`,
    myanimelist_id: 1600,
    price: `$18.81`,
  },

  {
    title: `Black Jack Kuroi Ishi`,
    description: `Black Jack Kuroi Ishi (Black Jack Dark Surgeon) was published in 2005 and 2006. It is a direct remake of the original Black Jack manga, with original Tezuka stories rewritten and redrawn in a more mod...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/14916.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/11050/Black_Jack_Kuroi_Ishi`,
    myanimelist_id: 11050,
    price: `$11.24`,
  },

  {
    title: `Black Jack no Yuuwaku`,
    description: `The billionaire's bedroom bargain... Jack Maguire was turned away from his father's house and has never forgotten that day—or how much he wanted his stepsister, Sally. Now a billionaire tycoon, by a t...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/102049.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/59051/Black_Jack_no_Yuuwaku`,
    myanimelist_id: 59051,
    price: `$20.24`,
  },

  {
    title: `Black Jack: Aoki Mirai`,
    description: `Set around the year 20xx, where Black Jack is nearly 60 years old.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/152336.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/29691/Black_Jack__Aoki_Mirai`,
    myanimelist_id: 29691,
    price: `$20.25`,
  },

  {
    title: `Dragon Ball`,
    description: `Bulma, a headstrong 16-year-old girl, is on a quest to find the mythical Dragon Balls—seven scattered magic orbs that grant the finder a single wish. She has but one desire in mind: a perfect boyfrien...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/267793.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/42/Dragon_Ball`,
    myanimelist_id: 42,
    price: `$13.73`,
  },

  {
    title: `Dragon Ball Super`,
    description: `Having defeated Boo, Goku is starting to get bored with his life on Earth. His wife, Chi-chi, wants him to get a job, but all he wants to do is train and fight stronger enemies. Elsewhere in the unive...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/176933.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/89734/Dragon_Ball_Super`,
    myanimelist_id: 89734,
    price: `$18.02`,
  },

  {
    title: `InuYasha`,
    description: `Kagome Higurashi's ordinary life comes to an abrupt halt when a demon drags her deep into a well, transporting her five hundred years into the past. In this era, Kagome quickly learns two things: demo...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/262295.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/676/InuYasha`,
    myanimelist_id: 676,
    price: `$11.74`,
  },

  {
    title: `Inuyashiki`,
    description: `Ichirou Inuyashiki is an old father worn down by the hardships of life, rendering him helpless and weak. Although he is friendless, unloved by his family, and diagnosed with cancer, he decides to try...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/156353.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/64465/Inuyashiki`,
    myanimelist_id: 64465,
    price: `$20.54`,
  },

  {
    title: `Nana`,
    description: `Nana Komatsu is a naive, unmotivated girl who spends her high school days chasing one crush after the other. Despite continually facing failure in her quest for love, her spirits have never dampened....read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/262324.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/28/Nana`,
    myanimelist_id: 28,
    price: `$20.02`,
  },

  {
    title: `Bishoujo Senshi Sailor Moon`,
    description: `"In the name of the moon, I shall punish you!" Usagi Tsukino is a cheerful 14-year-old who attends Juuban Municipal Junior High School. She prefers eating and playing video games to studying, which re...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/4/260613.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/92/Bishoujo_Senshi_Sailor_Moon`,
    myanimelist_id: 92,
    price: `$19.83`,
  },

  {
    title: `Wotaku ni Koi wa Muzukashii`,
    description: `Narumi Momose is a petite and cute young woman who loves idols, games, and everything anime or manga-related, especially in the boys' love genre. In other words, she is a closet otaku and more specifi...read more.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/155740.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/89087/Wotaku_ni_Koi_wa_Muzukashii`,
    myanimelist_id: 89087,
    price: `$19.90`,
  },

  {
    title: `Berserk`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/157897.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/2/Berserk`,
    myanimelist_id: 2,
    rank: 1,
    score: 9.47,
    type: `Manga (? vols)`,
    aired_on: `Aug 1989 -`,
    members: 689518,
    price: `$19.82`,
  },

  {
    title: `JoJo no Kimyou na Bouken Part 7: Steel Ball Run`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/179882.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1706/JoJo_no_Kimyou_na_Bouken_Part_7__Steel_Ball_Run`,
    myanimelist_id: 1706,
    rank: 2,
    score: 9.3,
    type: `Manga (24 vols)`,
    aired_on: `Jan 2004 - Apr 2011`,
    members: 265271,
    price: `$18.37`,
  },

  {
    title: `Vagabond`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/259070.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/656/Vagabond`,
    myanimelist_id: 656,
    rank: 3,
    score: 9.25,
    type: `Manga (37 vols)`,
    aired_on: `Sep 1998 - May 2015`,
    members: 381553,
    price: `$12.77`,
  },

  {
    title: `One Piece`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/253146.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/13/One_Piece`,
    myanimelist_id: 13,
    rank: 4,
    score: 9.22,
    type: `Manga (? vols)`,
    aired_on: `Jul 1997 -`,
    members: 617337,
    price: `$12.19`,
  },

  {
    title: `Monster`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/258224.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1/Monster`,
    myanimelist_id: 1,
    rank: 5,
    score: 9.16,
    type: `Manga (18 vols)`,
    aired_on: `Dec 1994 - Dec 2001`,
    members: 245045,
    price: `$21.79`,
  },

  {
    title: `Slam Dunk`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/258749.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/51/Slam_Dunk`,
    myanimelist_id: 51,
    rank: 6,
    score: 9.09,
    type: `Manga (31 vols)`,
    aired_on: `Sep 1990 - Jun 1996`,
    members: 170295,
    price: `$12.74`,
  },

  {
    title: `Vinland Saga`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/188925.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/642/Vinland_Saga`,
    myanimelist_id: 642,
    rank: 7,
    score: 9.07,
    type: `Manga (? vols)`,
    aired_on: `Apr 2005 -`,
    members: 303595,
    price: `$21.05`,
  },

  {
    title: `Fullmetal Alchemist`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/243675.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/25/Fullmetal_Alchemist`,
    myanimelist_id: 25,
    rank: 8,
    score: 9.04,
    type: `Manga (27 vols)`,
    aired_on: `Jul 2001 - Sep 2010`,
    members: 293768,
    price: `$14.18`,
  },

  {
    title: `Grand Blue`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/166124.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/70345/Grand_Blue`,
    myanimelist_id: 70345,
    rank: 9,
    score: 9.03,
    type: `Manga (? vols)`,
    aired_on: `Apr 2014 -`,
    members: 175973,
    price: `$12.23`,
  },

  {
    title: `Oyasumi Punpun`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/266834.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/4632/Oyasumi_Punpun`,
    myanimelist_id: 4632,
    rank: 10,
    score: 9.01,
    type: `Manga (13 vols)`,
    aired_on: `Mar 2007 - Nov 2013`,
    members: 443252,
    price: `$11.11`,
  },

  {
    title: `Kingdom`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/171872.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/16765/Kingdom`,
    myanimelist_id: 16765,
    rank: 11,
    score: 9.01,
    type: `Manga (? vols)`,
    aired_on: `Jan 2006 -`,
    members: 171737,
    price: `$15.06`,
  },

  {
    title: `Houseki no Kuni`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/115443.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/44489/Houseki_no_Kuni`,
    myanimelist_id: 44489,
    rank: 12,
    score: 8.97,
    type: `Manga (? vols)`,
    aired_on: `Oct 2012 -`,
    members: 130489,
    price: `$13.90`,
  },

  {
    title: `20th Century Boys`,
    picture_url: `https://cdn.myanimelist.net/images/manga/5/260006.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/3/20th_Century_Boys`,
    myanimelist_id: 3,
    rank: 13,
    score: 8.95,
    type: `Manga (22 vols)`,
    aired_on: `Sep 1999 - Apr 2006`,
    members: 257611,
    price: `$13.42`,
  },

  {
    title: `Real`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/115969.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/657/Real`,
    myanimelist_id: 657,
    rank: 14,
    score: 8.95,
    type: `Manga (? vols)`,
    aired_on: `Oct 1999 -`,
    members: 88231,
    price: `$19.66`,
  },

  {
    title: `Ashita no Joe`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/268827.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1303/Ashita_no_Joe`,
    myanimelist_id: 1303,
    rank: 15,
    score: 8.94,
    type: `Manga (20 vols)`,
    aired_on: `Jan 1968 - May 1973`,
    members: 52444,
    price: `$12.90`,
  },

  {
    title: `Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/188896.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/90125/Kaguya-sama_wa_Kokurasetai__Tensai-tachi_no_Renai_Zunousen`,
    myanimelist_id: 90125,
    rank: 16,
    score: 8.91,
    type: `Manga (28 vols)`,
    aired_on: `May 2015 - Nov 2022`,
    members: 269384,
    price: `$18.20`,
  },

  {
    title: `Yotsuba to!`,
    picture_url: `https://cdn.myanimelist.net/images/manga/5/259524.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/104/Yotsuba_to`,
    myanimelist_id: 104,
    rank: 17,
    score: 8.89,
    type: `Manga (? vols)`,
    aired_on: `Mar 2003 -`,
    members: 154446,
    price: `$12.01`,
  },

  {
    title: `GTO`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/172982.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/336/GTO`,
    myanimelist_id: 336,
    rank: 18,
    score: 8.88,
    type: `Manga (25 vols)`,
    aired_on: `Dec 1996 - Jan 2002`,
    members: 168611,
    price: `$11.01`,
  },

  {
    title: `3-gatsu no Lion`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/52283.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1224/3-gatsu_no_Lion`,
    myanimelist_id: 1224,
    rank: 19,
    score: 8.88,
    type: `Manga (? vols)`,
    aired_on: `Jul 2007 -`,
    members: 67470,
    price: `$12.55`,
  },

  {
    title: `Umineko no Naku Koro ni Chiru - Episode 8: Twilight of the Golden Witch`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/206205.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/34053/Umineko_no_Naku_Koro_ni_Chiru_-_Episode_8__Twilight_of_the_Golden_Witch`,
    myanimelist_id: 34053,
    rank: 20,
    score: 8.88,
    type: `Manga (9 vols)`,
    aired_on: `Jan 2012 - Jun 2015`,
    members: 16768,
    price: `$16.37`,
  },

  {
    title: `Koe no Katachi`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/120529.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/56805/Koe_no_Katachi`,
    myanimelist_id: 56805,
    rank: 21,
    score: 8.86,
    type: `Manga (7 vols)`,
    aired_on: `Aug 2013 - Nov 2014`,
    members: 269051,
    price: `$18.06`,
  },

  {
    title: `Haikyuu!!`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/258225.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/35243/Haikyuu`,
    myanimelist_id: 35243,
    rank: 22,
    score: 8.85,
    type: `Manga (45 vols)`,
    aired_on: `Feb 2012 - Jul 2020`,
    members: 216537,
    price: `$13.28`,
  },

  {
    title: `Kaze no Tani no Nausicaä`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/259856.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/651/Kaze_no_Tani_no_Nausicaä`,
    myanimelist_id: 651,
    rank: 23,
    score: 8.83,
    type: `Manga (7 vols)`,
    aired_on: `Oct 1982 - Feb 1994`,
    members: 58371,
    price: `$15.35`,
  },

  {
    title: `Akatsuki no Yona`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/269202.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/21525/Akatsuki_no_Yona`,
    myanimelist_id: 21525,
    rank: 24,
    score: 8.82,
    type: `Manga (? vols)`,
    aired_on: `Aug 2009 -`,
    members: 134696,
    price: `$16.44`,
  },

  {
    title: `Nana`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/262324.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/28/Nana`,
    myanimelist_id: 28,
    rank: 25,
    score: 8.8,
    type: `Manga (21 vols)`,
    aired_on: `May 2000 - May 2009`,
    members: 140798,
    price: `$16.19`,
  },

  {
    title: `Sousou no Frieren`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/232121.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/126287/Sousou_no_Frieren`,
    myanimelist_id: 126287,
    rank: 26,
    score: 8.79,
    type: `Manga (? vols)`,
    aired_on: `Apr 2020 -`,
    members: 117142,
    price: `$18.71`,
  },

  {
    title: `Jumyou wo Kaitotte Moratta. Ichinen ni Tsuki, Ichimanen de.`,
    picture_url: `https://cdn.myanimelist.net/images/manga/5/260043.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/100448/Jumyou_wo_Kaitotte_Moratta_Ichinen_ni_Tsuki_Ichimanen_de`,
    myanimelist_id: 100448,
    rank: 27,
    score: 8.78,
    type: `Manga (3 vols)`,
    aired_on: `Aug 2016 - Oct 2017`,
    members: 163835,
    price: `$15.76`,
  },

  {
    title: `Kokou no Hito`,
    picture_url: `https://cdn.myanimelist.net/images/manga/5/96223.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/7375/Kokou_no_Hito`,
    myanimelist_id: 7375,
    rank: 28,
    score: 8.77,
    type: `Manga (17 vols)`,
    aired_on: `Nov 2007 - Oct 2011`,
    members: 105776,
    price: `$12.84`,
  },

  {
    title: `Uchuu Kyoudai`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/166256.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/14483/Uchuu_Kyoudai`,
    myanimelist_id: 14483,
    rank: 29,
    score: 8.77,
    type: `Manga (? vols)`,
    aired_on: `Dec 2007 -`,
    members: 35221,
    price: `$16.12`,
  },

  {
    title: `Made in Abyss`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/161645.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/91941/Made_in_Abyss`,
    myanimelist_id: 91941,
    rank: 30,
    score: 8.76,
    type: `Manga (? vols)`,
    aired_on: `Oct 2012 -`,
    members: 160440,
    price: `$15.06`,
  },

  {
    title: `Hunter x Hunter`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/253119.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/26/Hunter_x_Hunter`,
    myanimelist_id: 26,
    rank: 31,
    score: 8.74,
    type: `Manga (? vols)`,
    aired_on: `Mar 1998 -`,
    members: 271657,
    price: `$19.28`,
  },

  {
    title: `One Punch-Man`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/80661.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/44347/One_Punch-Man`,
    myanimelist_id: 44347,
    rank: 32,
    score: 8.74,
    type: `Manga (? vols)`,
    aired_on: `Jun 2012 -`,
    members: 481077,
    price: `$18.96`,
  },

  {
    title: `Chainsaw Man`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/216464.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/116778/Chainsaw_Man`,
    myanimelist_id: 116778,
    rank: 33,
    score: 8.73,
    type: `Manga (? vols)`,
    aired_on: `Dec 2018 -`,
    members: 614119,
    price: `$20.92`,
  },

  {
    title: `Hajime no Ippo`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/250313.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/7/Hajime_no_Ippo`,
    myanimelist_id: 7,
    rank: 34,
    score: 8.73,
    type: `Manga (? vols)`,
    aired_on: `Sep 1989 -`,
    members: 86634,
    price: `$19.16`,
  },

  {
    title: `Shoujo Shuumatsu Ryokou`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/185918.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/72467/Shoujo_Shuumatsu_Ryokou`,
    myanimelist_id: 72467,
    rank: 35,
    score: 8.72,
    type: `Manga (6 vols)`,
    aired_on: `Feb 2014 - Jan 2018`,
    members: 68414,
    price: `$15.11`,
  },

  {
    title: `Mushishi`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/159514.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/418/Mushishi`,
    myanimelist_id: 418,
    rank: 36,
    score: 8.72,
    type: `Manga (10 vols)`,
    aired_on: `Nov 1999 - Aug 2008`,
    members: 83587,
    price: `$15.80`,
  },

  {
    title: `Death Note`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/258245.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/21/Death_Note`,
    myanimelist_id: 21,
    rank: 37,
    score: 8.69,
    type: `Manga (12 vols)`,
    aired_on: `Dec 2003 - May 2006`,
    members: 394390,
    price: `$21.65`,
  },

  {
    title: `Beck`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/253274.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/145/Beck`,
    myanimelist_id: 145,
    rank: 38,
    score: 8.69,
    type: `Manga (34 vols)`,
    aired_on: `Feb 2000 - Jun 2008`,
    members: 78986,
    price: `$18.43`,
  },

  {
    title: `Kono Oto Tomare!`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/116653.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/45143/Kono_Oto_Tomare`,
    myanimelist_id: 45143,
    rank: 39,
    score: 8.69,
    type: `Manga (? vols)`,
    aired_on: `Aug 2012 -`,
    members: 42944,
    price: `$18.80`,
  },

  {
    title: `Yokohama Kaidashi Kikou`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/171813.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/4/Yokohama_Kaidashi_Kikou`,
    myanimelist_id: 4,
    rank: 40,
    score: 8.68,
    type: `Manga (14 vols)`,
    aired_on: `Apr 1994 - Feb 2006`,
    members: 74344,
    price: `$14.81`,
  },

  {
    title: `Dorohedoro`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/258246.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1133/Dorohedoro`,
    myanimelist_id: 1133,
    rank: 41,
    score: 8.68,
    type: `Manga (23 vols)`,
    aired_on: `Nov 2000 - Sep 2018`,
    members: 174472,
    price: `$21.75`,
  },

  {
    title: `Akira`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/271629.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/664/Akira`,
    myanimelist_id: 664,
    rank: 42,
    score: 8.67,
    type: `Manga (6 vols)`,
    aired_on: `Dec 1982 - Jun 1990`,
    members: 131747,
    price: `$12.69`,
  },

  {
    title: `Natsume Yuujinchou`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/260099.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/1859/Natsume_Yuujinchou`,
    myanimelist_id: 1859,
    rank: 43,
    score: 8.67,
    type: `Manga (? vols)`,
    aired_on: `Jun 2003 -`,
    members: 43894,
    price: `$19.12`,
  },

  {
    title: `Yagate Kimi ni Naru`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/232311.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/88660/Yagate_Kimi_ni_Naru`,
    myanimelist_id: 88660,
    rank: 44,
    score: 8.67,
    type: `Manga (8 vols)`,
    aired_on: `Apr 2015 - Sep 2019`,
    members: 104474,
    price: `$15.82`,
  },

  {
    title: `Bungou Stray Dogs: Beast`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/234643.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/123006/Bungou_Stray_Dogs__Beast`,
    myanimelist_id: 123006,
    rank: 45,
    score: 8.67,
    type: `Manga (4 vols)`,
    aired_on: `Dec 2019 - Jan 2022`,
    members: 14512,
    price: `$15.75`,
  },

  {
    title: `Veil`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/239756.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/132678/Veil`,
    myanimelist_id: 132678,
    rank: 46,
    score: 8.66,
    type: `Manga (? vols)`,
    aired_on: `Nov 2019 -`,
    members: 9693,
    price: `$21.29`,
  },

  {
    title: `Kozure Ookami`,
    picture_url: `https://cdn.myanimelist.net/images/manga/1/159264.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/904/Kozure_Ookami`,
    myanimelist_id: 904,
    rank: 47,
    score: 8.66,
    type: `Manga (28 vols)`,
    aired_on: `Sep 1970 - Apr 1976`,
    members: 46654,
    price: `$17.63`,
  },

  {
    title: `Sayonara Eri`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/263979.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/145863/Sayonara_Eri`,
    myanimelist_id: 145863,
    rank: 48,
    score: 8.66,
    type: `Manga (1 vols)`,
    aired_on: `Apr 2022 - Apr 2022`,
    members: 113871,
    price: `$11.52`,
  },

  {
    title: `Golden Kamuy`,
    picture_url: `https://cdn.myanimelist.net/images/manga/3/149257.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/85968/Golden_Kamuy`,
    myanimelist_id: 85968,
    rank: 49,
    score: 8.65,
    type: `Manga (31 vols)`,
    aired_on: `Aug 2014 - Apr 2022`,
    members: 92202,
    price: `$17.55`,
  },

  {
    title: `ReLIFE`,
    picture_url: `https://cdn.myanimelist.net/images/manga/2/171573.jpg`,
    myanimelist_url: `https://myanimelist.net/manga/78523/ReLIFE`,
    myanimelist_id: 78523,
    rank: 50,
    score: 8.64,
    type: `Manga (15 vols)`,
    aired_on: `Oct 2013 - Mar 2018`,
    members: 161319,
    price: `$18.80`,
  },
];

module.exports = hardcodedManga;
